### ISSUE TITLE
Changement de langues

### ISSUE THREAD

**Issue by AxelANGENAULT** [AriiPortal/DSBundle#1]
Bonjour Eric,

Après traduction, les mots `Jour` et `Aujourd'hui` ne sont pas traduits car ne sont pas définis en tant que "clef" (vérifié sur `app_dev.php/_profiler/d9e991?panel=translation`).
![plan_trad](https://cloud.githubusercontent.com/assets/11269587/12548237/41c5a882-c355-11e5-8f43-ef930306051a.png)
La traduction figure déjà dans le fichier message.en.yml que je fini de vérifier avant soumission, 
merci d'utiliser une clef pour ses termes.

Bonne journée :smiley:

**Comment by AriiPortal** [comment]
Corrigé mais à voir plus précisemment car cette partie est normalement prise en charge par les fichiers de traduction du frontal (dhtmlx).
